#!/data/data/com.termux/files/usr/bin/bash
#if [ "$1" = "wget --no-check-certificate --continue --show-progress --output-file=$OUTPUT_FILE $URL
WGET="wget --no-check-certificate --continue --show-progress"
if [[ -z "$2" ]]; then
	$WGET "$1"
else
	$WGET --output-file="$2" "$1"
fi
